"""
PDF Service — Generates an A4 Landscape PDF with three topographic map images.

Uses FPDF2 to lay out the three composited map images (Satellite, Terrain, Streets)
in a row with labels, title header, coordinate info, and footer.
"""

import io
import math
from datetime import datetime

from fpdf import FPDF
from PIL import Image

def haversine(lat1, lon1, lat2, lon2):
    """Calculate distance in meters between two lat/lon points."""
    R = 6371000  # Radius of earth in meters
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)
    a = math.sin(delta_phi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(delta_lambda / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c


# A4 Landscape dimensions in mm
PAGE_WIDTH = 297
PAGE_HEIGHT = 210


class TopoPDF(FPDF):
    """Custom FPDF subclass for topographic map reports."""

    def __init__(self, bbox_info: dict):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.bbox_info = bbox_info
        self.set_auto_page_break(auto=False)

    def header(self):
        """Render the PDF header with title and coordinates."""
        # Title
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(30, 30, 30)
        self.cell(0, 12, "3D Topographic Map Report", align="C", new_x="LMARGIN", new_y="NEXT")

        # Coordinate info line
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        bbox = self.bbox_info
        coord_text = (
            f"Bounding Box:  N {bbox['north']:.4f}°  |  S {bbox['south']:.4f}°  |  "
            f"E {bbox['east']:.4f}°  |  W {bbox['west']:.4f}°"
        )
        self.cell(0, 6, coord_text, align="C", new_x="LMARGIN", new_y="NEXT")

        # Timestamp
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0,
            5,
            f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        # Separator line
        self.ln(2)
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), PAGE_WIDTH - 15, self.get_y())
        self.ln(4)

    def footer(self):
        """Render the PDF footer."""
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(
            0,
            5,
            "Generated by 3D TopoMapping  |  Elevation Data: USGS SRTM  |  "
            "Basemaps: Esri, OpenTopoMap, OpenStreetMap",
            align="C",
        )


def _pil_to_bytes(img: Image.Image, fmt: str = "PNG") -> io.BytesIO:
    """Convert a PIL Image to a BytesIO buffer."""
    buf = io.BytesIO()
    img.save(buf, format=fmt)
    buf.seek(0)
    return buf


def generate_pdf(
    satellite_img: Image.Image,
    terrain_img: Image.Image,
    streets_img: Image.Image,
    bbox_info: dict,
    color_legend_img: Image.Image = None,
) -> io.BytesIO:
    """
    Generate an A4 Landscape PDF with three topographic map images.

    Args:
        satellite_img: Composited satellite + contour image
        terrain_img: Composited terrain + contour image
        streets_img: Composited streets + contour image
        bbox_info: Dict with 'north', 'south', 'east', 'west' keys

    Returns:
        BytesIO buffer containing the PDF
    """
    pdf = TopoPDF(bbox_info)

    # Layout calculations
    margin = 15  # mm from edges
    usable_width = PAGE_WIDTH - (2 * margin)
    img_width = usable_width

    # Image data and labels
    images = [
        (satellite_img, "Satellite View", "Esri World Imagery + SRTM Contours"),
        (terrain_img, "Terrain View", "OpenTopoMap + SRTM Contours"),
        (streets_img, "Streets View", "OpenStreetMap + SRTM Contours"),
    ]

    for img, title, subtitle in images:
        pdf.add_page()
        
        # Start Y position (after header)
        y_start = pdf.get_y() + 2

        # Available area for images
        max_h = PAGE_HEIGHT - y_start - 25  # 25mm for label + footer
        max_w = usable_width
        
        # Calculate proportional size
        img_ratio = img.width / img.height
        box_ratio = max_w / max_h
        
        if img_ratio > box_ratio:
            # Image is wider than box -> constrain to width
            render_w = max_w
            render_h = max_w / img_ratio
        else:
            # Image is taller than box -> constrain to height
            render_h = max_h
            render_w = max_h * img_ratio
            
        # Center horizontally and vertically within the available space
        x = margin + (max_w - render_w) / 2
        y = y_start + (max_h - render_h) / 2

        # Add a subtle border/background behind the image
        pdf.set_fill_color(245, 245, 245)
        pdf.set_draw_color(220, 220, 220)
        pdf.rect(x - 1, y - 1, render_w + 2, render_h + 2, style="D")

        # Place the image
        img_buf = _pil_to_bytes(img)
        pdf.image(img_buf, x=x, y=y, w=render_w, h=render_h)

        # --- Graticules (Grid Lines) ---
        pdf.set_draw_color(255, 255, 255)
        pdf.set_line_width(0.3)
        pdf.set_dash_pattern(dash=2, gap=2)
        
        north, south = bbox_info['north'], bbox_info['south']
        east, west = bbox_info['east'], bbox_info['west']
        
        pdf.set_fill_color(255, 255, 255) # For label backgrounds
        for i in range(1, 4):
            # Vertical lines
            lx = x + (render_w * i / 4)
            lon = west + (east - west) * i / 4
            pdf.line(lx, y, lx, y + render_h)
            
            # Label
            pdf.set_xy(lx - 10, y + render_h)
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(20, 4, f"{lon:.4f}° E", align="C", fill=True)
            
            # Horizontal lines
            ly = y + (render_h * i / 4)
            lat = north - (north - south) * i / 4
            pdf.line(x, ly, x + render_w, ly)
            
            # Label
            pdf.set_xy(x - 17, ly - 2)
            pdf.cell(16, 4, f"{lat:.4f}° N", align="R", fill=True)
            
        pdf.set_dash_pattern() # Reset dash
        
        # --- Scale Bar ---
        avg_lat = (north + south) / 2
        map_width_meters = haversine(avg_lat, west, avg_lat, east)
        mm_per_meter = render_w / map_width_meters
        
        target_scale_m = 50
        if map_width_meters > 5000:
            target_scale_m = 1000
        elif map_width_meters > 1000:
            target_scale_m = 500
        elif map_width_meters > 500:
            target_scale_m = 100
        elif map_width_meters < 100:
            target_scale_m = 10
            
        scale_width_mm = target_scale_m * mm_per_meter
        
        sx = x + render_w - scale_width_mm - 5
        sy = y + render_h - 10
        
        # Draw white background for scale bar visibility
        pdf.set_fill_color(255, 255, 255)
        pdf.rect(sx - 2, sy - 8, scale_width_mm + 4, 12, style="F")
        
        pdf.set_draw_color(0, 0, 0)
        pdf.set_line_width(0.8)
        pdf.line(sx, sy, sx + scale_width_mm, sy) # Main line
        pdf.line(sx, sy - 2, sx, sy + 2) # Left tick
        pdf.line(sx + scale_width_mm, sy - 2, sx + scale_width_mm, sy + 2) # Right tick
        
        pdf.set_xy(sx, sy - 7)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(scale_width_mm, 4, f"{target_scale_m} m", align="C")
        
        # --- North Arrow ---
        nx = x + render_w - 15
        ny = y + 10
        
        pdf.set_fill_color(255, 255, 255)
        pdf.rect(nx - 7, ny - 7, 14, 20, style="F")
        
        pdf.set_draw_color(0, 0, 0)
        pdf.set_line_width(0.8)
        pdf.line(nx, ny, nx, ny + 10) # Shaft
        pdf.line(nx, ny, nx - 2, ny + 3) # Left point
        pdf.line(nx, ny, nx + 2, ny + 3) # Right point
        
        pdf.set_xy(nx - 5, ny - 6)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(10, 5, "N", align="C")

        # --- Labels and Legend ---
        # Title label below image
        pdf.set_xy(margin, y_start + max_h + 2)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(max_w, 6, title, align="C", new_x="LMARGIN", new_y="NEXT")

        # Subtitle label
        pdf.set_xy(margin, y_start + max_h + 8)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(max_w, 5, subtitle, align="C")
        
        # Paste Color Legend at the bottom right
        if color_legend_img:
            legend_buf = _pil_to_bytes(color_legend_img)
            legend_w = 90
            legend_h = 11
            lx = margin + max_w - legend_w
            ly = y_start + max_h + 2
            pdf.image(legend_buf, x=lx, y=ly, w=legend_w, h=legend_h)

    # Output to buffer
    output_buf = io.BytesIO()
    pdf.output(output_buf)
    output_buf.seek(0)
    return output_buf
